import { z } from "zod";

export const questionnaireSchema = z.object({
  // 1. BRANDING & REBRANDING
  brandingRebranding: z.object({
    estrategiaDeMarca: z.object({
      desenvolvimentoIdentidadeVisual: z.boolean().default(false),
      criacaoNamingTaglines: z.boolean().default(false),
      arquiteturaMarca: z.boolean().default(false),
      posicionamentoEstrategico: z.boolean().default(false),
      brandGuidelinesManuais: z.boolean().default(false),
      pesquisaMercadoPersonas: z.boolean().default(false),
      analiseConcorrencia: z.boolean().default(false),
    }),
    rebranding: z.object({
      auditoriaMarcaExistente: z.boolean().default(false),
      estrategiaTransicaoMarca: z.boolean().default(false),
      gestaoMudancaOrganizacional: z.boolean().default(false),
      comunicacaoRebranding: z.boolean().default(false),
    }),
  }),

  // 2. COPYWRITING
  copywriting: z.object({
    tecnicasDeEscrita: z.object({
      headlinesTitulosPersuasivos: z.boolean().default(false),
      callToActionEfetivos: z.boolean().default(false),
      storytellingComercial: z.boolean().default(false),
      copywritingConversao: z.boolean().default(false),
      seoCopywriting: z.boolean().default(false),
      microcopyUxWriting: z.boolean().default(false),
    }),
    formatos: z.object({
      anunciosPagos: z.boolean().default(false),
      emailMarketing: z.boolean().default(false),
      scriptsVideo: z.boolean().default(false),
      copyRedesSociais: z.boolean().default(false),
      salesPages: z.boolean().default(false),
    }),
    nivelGeral: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
  }),

  // 3. REDAÇÃO
  redacao: z.object({
    conteudoEditorial: z.object({
      artigosBlogSeo: z.boolean().default(false),
      pressReleases: z.boolean().default(false),
      casosEstudo: z.boolean().default(false),
      ebooksWhitepapers: z.boolean().default(false),
      newsletters: z.boolean().default(false),
      roteirosScripts: z.boolean().default(false),
    }),
    tomVoz: z.object({
      adaptacaoLinguagemPublico: z.boolean().default(false),
      redacaoTecnica: z.boolean().default(false),
      redacaoCriativa: z.boolean().default(false),
      revisaoEdicaoTextos: z.boolean().default(false),
      gramaticaOrtografiaPtBr: z.boolean().default(false),
    }),
    nivelGeral: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
  }),

  // 4. ARTE & DESIGN
  arteDesign: z.object({
    designGrafico: z.object({
      adobePhotoshop: z.boolean().default(false),
      adobeIllustrator: z.boolean().default(false),
      adobeInDesign: z.boolean().default(false),
      figma: z.boolean().default(false),
      canvaPro: z.boolean().default(false),
      corelDRAW: z.boolean().default(false),
    }),
    habilidadesCriativas: z.object({
      teoriaCores: z.boolean().default(false),
      tipografia: z.boolean().default(false),
      composicaoVisual: z.boolean().default(false),
      ilustracaoDigital: z.boolean().default(false),
      manipulacaoImagens: z.boolean().default(false),
      motionGraphicsBasico: z.boolean().default(false),
      designApresentacoes: z.boolean().default(false),
    }),
    materiais: z.object({
      pecasRedesSociais: z.boolean().default(false),
      bannersOutdoors: z.boolean().default(false),
      materiaisImpressos: z.boolean().default(false),
      embalagens: z.boolean().default(false),
      identidadeVisualCompleta: z.boolean().default(false),
    }),
    nivelGeral: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
  }),

  // 5. MÍDIA SOCIAL (SOCIAL MEDIA)
  midiaSocial: z.object({
    plataformas: z.object({
      instagram: z.boolean().default(false),
      facebook: z.boolean().default(false),
      linkedin: z.boolean().default(false),
      tiktok: z.boolean().default(false),
      youtube: z.boolean().default(false),
      twitterX: z.boolean().default(false),
      pinterest: z.boolean().default(false),
    }),
    gestao: z.object({
      planejamentoConteudo: z.boolean().default(false),
      calendarioEditorial: z.boolean().default(false),
      analiseMetricasKpis: z.boolean().default(false),
      gerenciamentoComunidade: z.boolean().default(false),
      atendimentoCliente: z.boolean().default(false),
      gestaoCrises: z.boolean().default(false),
    }),
    ferramentas: z.object({
      metaBusinessSuite: z.boolean().default(false),
      hootsuiteBuffer: z.boolean().default(false),
      sproutSocial: z.boolean().default(false),
      laterPlanable: z.boolean().default(false),
      analiseNativaPlataformas: z.boolean().default(false),
    }),
    nivelGeral: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
  }),

  // 6. LANDING PAGES
  landingPages: z.object({
    desenvolvimento: z.object({
      htmlCssBasico: z.boolean().default(false),
      wordpress: z.boolean().default(false),
      elementorWpBakery: z.boolean().default(false),
      unbounce: z.boolean().default(false),
      leadpages: z.boolean().default(false),
      webflow: z.boolean().default(false),
      rdStationHubSpot: z.boolean().default(false),
    }),
    otimizacao: z.object({
      uxUiConversao: z.boolean().default(false),
      testesAb: z.boolean().default(false),
      otimizacaoFormularios: z.boolean().default(false),
      copywritingLandingPages: z.boolean().default(false),
      analiseHeatmaps: z.boolean().default(false),
      pageSpeedOptimization: z.boolean().default(false),
      mobileResponsiveness: z.boolean().default(false),
    }),
    integracoes: z.object({
      googleAnalytics: z.boolean().default(false),
      googleTagManager: z.boolean().default(false),
      pixelFacebookMeta: z.boolean().default(false),
      crm: z.boolean().default(false),
      ferramentasAutomacao: z.boolean().default(false),
    }),
    nivelGeral: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
  }),

  // 7. PUBLICIDADE
  publicidade: z.object({
    midiaPaga: z.object({
      googleAds: z.boolean().default(false),
      metaAds: z.boolean().default(false),
      linkedinAds: z.boolean().default(false),
      tiktokAds: z.boolean().default(false),
      pinterestAds: z.boolean().default(false),
      programatica: z.boolean().default(false),
    }),
    estrategia: z.object({
      definicaoPublicoAlvo: z.boolean().default(false),
      segmentacaoAvancada: z.boolean().default(false),
      budgetLances: z.boolean().default(false),
      funisConversao: z.boolean().default(false),
      remarketingRetargeting: z.boolean().default(false),
      analiseRoiRoas: z.boolean().default(false),
    }),
    creative: z.object({
      criacaoAnuncios: z.boolean().default(false),
      testesCriativos: z.boolean().default(false),
      videoAds: z.boolean().default(false),
      carouselColecoes: z.boolean().default(false),
    }),
    nivelGeral: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
  }),

  // 8. MARKETING
  marketing: z.object({
    marketingDigital: z.object({
      seo: z.boolean().default(false),
      marketingConteudo: z.boolean().default(false),
      emailMarketing: z.boolean().default(false),
      marketingPerformance: z.boolean().default(false),
      growthHacking: z.boolean().default(false),
      marketingInfluencia: z.boolean().default(false),
    }),
    estrategia: z.object({
      planejamentoEstrategico: z.boolean().default(false),
      definicaoKpis: z.boolean().default(false),
      analiseMercado: z.boolean().default(false),
      buyerPersonas: z.boolean().default(false),
      funilVendas: z.boolean().default(false),
      customerJourneyMapping: z.boolean().default(false),
    }),
    analiseDados: z.object({
      googleAnalyticsGa4: z.boolean().default(false),
      googleSearchConsole: z.boolean().default(false),
      dataStudioLookerStudio: z.boolean().default(false),
      excelGoogleSheetsAvancado: z.boolean().default(false),
      interpretacaoMetricas: z.boolean().default(false),
      relatoriosPerformance: z.boolean().default(false),
    }),
    automacao: z.object({
      rdStation: z.boolean().default(false),
      hubSpot: z.boolean().default(false),
      mailchimp: z.boolean().default(false),
      activeCampaign: z.boolean().default(false),
      zapierMake: z.boolean().default(false),
    }),
    nivelGeral: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
  }),

  // 9. TECNOLOGIA & AUTOMAÇÕES
  tecnologiaAutomacoes: z.object({
    infraestruturaTecnologica: z.object({
      dominiosDns: z.boolean().default(false),
      hospedagemWeb: z.boolean().default(false),
      servidoresCloudComputing: z.boolean().default(false),
      sslCertificadosSeguranca: z.boolean().default(false),
      cdn: z.boolean().default(false),
      backupRecuperacaoDados: z.boolean().default(false),
    }),
    desenvolvimentoWeb: z.object({
      htmlCss3: z.boolean().default(false),
      javaScriptBasico: z.boolean().default(false),
      wordpressInstalacaoConfiguracao: z.boolean().default(false),
      pluginsEssenciaisWordpress: z.boolean().default(false),
      phpBasico: z.boolean().default(false),
      apisIntegracoes: z.boolean().default(false),
      versionamentoGitGithub: z.boolean().default(false),
      responsiveDesign: z.boolean().default(false),
    }),
    cmsPlataformas: z.object({
      wordpress: z.boolean().default(false),
      webflow: z.boolean().default(false),
      shopify: z.boolean().default(false),
      wixSquarespace: z.boolean().default(false),
      drupalJoomla: z.boolean().default(false),
      headlessCms: z.boolean().default(false),
    }),
    automacaoMarketing: z.object({
      rdStationMarketing: z.boolean().default(false),
      hubSpotWorkflows: z.boolean().default(false),
      activeCampaignAutomacoes: z.boolean().default(false),
      mailchimpCustomerJourneys: z.boolean().default(false),
      klaviyoEcommerceAutomation: z.boolean().default(false),
      marketingCloudSalesforce: z.boolean().default(false),
    }),
    automacaoProcessosNoCodeLowCode: z.object({
      zapier: z.boolean().default(false),
      makeIntegromat: z.boolean().default(false),
      n8n: z.boolean().default(false),
      pabblyConnect: z.boolean().default(false),
      automateIo: z.boolean().default(false),
      microsoftPowerAutomate: z.boolean().default(false),
      ifttt: z.boolean().default(false),
    }),
    automacaoRedesSociais: z.object({
      agendamentoAutomatico: z.boolean().default(false),
      chatbotsInstagramFacebook: z.boolean().default(false),
      manyChat: z.boolean().default(false),
      chatfuel: z.boolean().default(false),
      respostaAutomaticaDm: z.boolean().default(false),
      automacaoStoriesPosts: z.boolean().default(false),
    }),
    crmGestaoClientes: z.object({
      hubSpotCrm: z.boolean().default(false),
      rdStationCrm: z.boolean().default(false),
      salesforce: z.boolean().default(false),
      pipedrive: z.boolean().default(false),
      bitrix24: z.boolean().default(false),
      zohoCrm: z.boolean().default(false),
      mondaySalesCrm: z.boolean().default(false),
    }),
    automacaoWhatsappBusiness: z.object({
      whatsappBusinessApi: z.boolean().default(false),
      chatbotsWhatsapp: z.boolean().default(false),
      integracaoCrm: z.boolean().default(false),
      disparosMassa: z.boolean().default(false),
      automacaoAtendimento: z.boolean().default(false),
      plataformasTwilioZenviaTakeBlip: z.boolean().default(false),
    }),
    iaFerramentasInteligentes: z.object({
      chatGptClaude: z.boolean().default(false),
      midjourneyDallE: z.boolean().default(false),
      jasperAi: z.boolean().default(false),
      copyAi: z.boolean().default(false),
      runwayMl: z.boolean().default(false),
      removeBg: z.boolean().default(false),
      grammarly: z.boolean().default(false),
      iaAnaliseDados: z.boolean().default(false),
    }),
    automacaoRelatorios: z.object({
      googleDataStudioLookerStudio: z.boolean().default(false),
      powerBi: z.boolean().default(false),
      tableau: z.boolean().default(false),
      dashboardsAutomaticos: z.boolean().default(false),
      integracaoMultiplasFontesDados: z.boolean().default(false),
      relatoriosAgendadosAutomaticamente: z.boolean().default(false),
      googleSheetsScripts: z.boolean().default(false),
    }),
    ferramentasColaboracao: z.object({
      slack: z.boolean().default(false),
      microsoftTeams: z.boolean().default(false),
      discord: z.boolean().default(false),
      notionBaseConhecimento: z.boolean().default(false),
      googleWorkspace: z.boolean().default(false),
      asanaTrelloMonday: z.boolean().default(false),
    }),
    ecommercePagamentos: z.object({
      integracaoGatewaysPagamento: z.boolean().default(false),
      stripe: z.boolean().default(false),
      paypal: z.boolean().default(false),
      mercadoPago: z.boolean().default(false),
      pagSeguro: z.boolean().default(false),
      automacaoCarrinhoAbandonado: z.boolean().default(false),
      upsellCrossSellAutomatizados: z.boolean().default(false),
    }),
    automacaoEmail: z.object({
      sequenciasNutricao: z.boolean().default(false),
      segmentacaoDinamica: z.boolean().default(false),
      triggersComportamentais: z.boolean().default(false),
      abTestingAutomatizado: z.boolean().default(false),
      reEngajamentoAutomatico: z.boolean().default(false),
      integracaoEventosSite: z.boolean().default(false),
    }),
    ferramentasProdutividade: z.object({
      loom: z.boolean().default(false),
      calendly: z.boolean().default(false),
      typeformGoogleForms: z.boolean().default(false),
      docusignAssinaturasDigitais: z.boolean().default(false),
      notionCodaDocumentacao: z.boolean().default(false),
      airtableBancoDadosVisual: z.boolean().default(false),
    }),
    seoTecnicoFerramentas: z.object({
      googleSearchConsole: z.boolean().default(false),
      semrushAhrefs: z.boolean().default(false),
      screamingFrog: z.boolean().default(false),
      schemaMarkup: z.boolean().default(false),
      sitemapXml: z.boolean().default(false),
      robotsTxt: z.boolean().default(false),
      coreWebVitals: z.boolean().default(false),
    }),
    segurancaCompliance: z.object({
      lgpd: z.boolean().default(false),
      cookiesConsentimento: z.boolean().default(false),
      politicasPrivacidade: z.boolean().default(false),
      segurancaDadosClientes: z.boolean().default(false),
      autenticacaoDoisFatores: z.boolean().default(false),
      firewallProtecaoMalware: z.boolean().default(false),
    }),
    analyticsTagManagement: z.object({
      googleAnalytics4: z.boolean().default(false),
      googleTagManager: z.boolean().default(false),
      facebookPixel: z.boolean().default(false),
      hotjarCrazyEgg: z.boolean().default(false),
      mixpanel: z.boolean().default(false),
      configuracaoEventosCustomizados: z.boolean().default(false),
    }),
    automacaoPropostasContratos: z.object({
      pandadoc: z.boolean().default(false),
      proposify: z.boolean().default(false),
      docusign: z.boolean().default(false),
      hellosign: z.boolean().default(false),
      templatesAutomatizados: z.boolean().default(false),
      followUpAutomaticoPropostas: z.boolean().default(false),
    }),
    gestaoFinanceiraAutomatizada: z.object({
      integracaoBancaria: z.boolean().default(false),
      emissaoNotasFiscaisAutomaticas: z.boolean().default(false),
      cobrancasRecorrentes: z.boolean().default(false),
      controleFluxoCaixa: z.boolean().default(false),
      ferramentasContaAzulOmieBling: z.boolean().default(false),
    }),
    backupRecuperacao: z.object({
      backupAutomaticoSites: z.boolean().default(false),
      backupDadosCrm: z.boolean().default(false),
      versionamentoArquivos: z.boolean().default(false),
      planoDisasterRecovery: z.boolean().default(false),
      cloudBackup: z.boolean().default(false),
    }),
    nivelGeral: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
  }),

  // 10. HABILIDADES COMPLEMENTARES
  habilidadesComplementares: z.object({
    gestaoProjetos: z.object({
      metodologiasAgeis: z.boolean().default(false),
      trelloAsanaMonday: z.boolean().default(false),
      gestaoPrazos: z.boolean().default(false),
      briefingDebriefing: z.boolean().default(false),
      gestaoEquipe: z.boolean().default(false),
    }),
    atendimentoCliente: z.object({
      relacionamentoCliente: z.boolean().default(false),
      apresentacoesComerciais: z.boolean().default(false),
      negociacao: z.boolean().default(false),
      propostasComerciais: z.boolean().default(false),
    }),
    outrasSkills: z.object({
      fotografiaBasica: z.boolean().default(false),
      edicaoVideo: z.boolean().default(false),
      producaoAudiovisual: z.boolean().default(false),
      audioPodcast: z.boolean().default(false),
      nocoesProgramacao: z.boolean().default(false),
    }),
    nivelGeral: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
  }),

  // 11. SOFT SKILLS
  softSkills: z.object({
    criatividade: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
    comunicacao: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
    trabalhoEmEquipe: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
    gestaoDeTempo: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
    proatividade: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
    resolucaoDeProblemas: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
    adaptabilidade: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
    atencaoAosDetalhes: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
    sensoDeUrgencia: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
    capacidadeAnalitica: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
    nivelGeral: z.coerce.number().min(1, { message: "O nível deve ser entre 1 e 5." }).max(5, { message: "O nível deve ser entre 1 e 5." }).default(1),
  }),
});

export type QuestionnaireSchema = z.infer<typeof questionnaireSchema>;